---
title: "Results"
author: "Masumbuko Semba"
date: "February 14, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = "")
```

```{r}
require(tidyverse)
require(oce)
require(highcharter)
require(lubridate)
```
### chlorophyll
```{r}
setwd("e:/Data Manipulation/kuguru/extracted/")

files = dir("./", pattern = "chl_")
sites = c("EEZ", "Mafia", "Pemba", "Zanzibar")
```


```{r}

chl = list()
for (i in 1:length(files)){

chl[[i]] = files[i] %>% readxl::read_excel()%>% 
  rename(date = 1, year = 2, chl = 3) %>% 
  mutate(month = month(date), 
         day = 15,
         site = sites[i], 
         date = make_date(year = year, month = month, day = day),
         variable = "chl") %>%
  arrange(date)
}

chl = chl %>% bind_rows()

```


```{r, fig.height=5, fig.width=10, eval=FALSE}
gg = ggplot()+
  geom_raster(data = chl, aes(x = year, y = month, fill =  chl), interpolate = T, na.rm = TRUE)+
  geom_contour(data = chl, aes(x = year, y = month, z =  chl), col = 1)+
  scale_y_reverse(breaks = 1:12)+
  scale_fill_gradientn(colours = oceColors9A(120))+
  facet_wrap(~site, scales = "free_y")

plotly::ggplotly(gg)
```

```{r}
hchart(object = chl%>%filter(site == "Mafia"), "heatmap", hcaes(x = year, y = month, value = chl, group = site))
```

```{r ,eval=FALSE}
gb =ggplot(data = chl, aes(x = date, y = chl, col = site))+geom_line()
    plotly::ggplotly(gb)
```

```{r}
hchart(object = chl, "line", hcaes(x = date, y = chl, group = site))
```


```{r , fig.width=9}
month = 1:12
year = 2003:2018

chl.array = array(data = chl$chl, dim = c(length(month),length(year),length(sites)))

par(mfrow = c(2,2))
for (j in 1:length(sites)){
imagep(year, month, chl.array[,,j]%>%t(),filledContour = T, col = oceColors9A(120),  flipy = T, main = sites[j])
contour(year, month,chl.array[,,j]%>%t() , add = T)
}

```


### Primary productivity
```{r}
files = dir("./", pattern = "pp_")
sites = c("EEZ", "Mafia", "Pemba", "Zanzibar")
```


```{r}

pp = list()
for (i in 1:length(files)){

pp[[i]] = files[i] %>% readxl::read_excel()%>% 
  rename(date = 1, year = 2, pp = 3) %>% 
  mutate(month = month(date), 
         day = 15,
         site = sites[i], 
         date = make_date(year = year, month = month, day = day),
         variable = "pp") %>%
  arrange(date)
}

pp = pp %>% bind_rows()

```


```{r, fig.height=5, fig.width=10,eval=FALSE}
gg = ggplot()+
  geom_raster(data = pp, aes(x = year, y = month, fill =  pp), interpolate = T, na.rm = TRUE)+
  geom_contour(data = pp, aes(x = year, y = month, z =  pp), col = 1)+
  scale_y_reverse(breaks = 1:12)+
  scale_fill_gradientn(colours = oceColors9A(120))+
  facet_wrap(~site, scales = "free_y")

plotly::ggplotly(gg)
```

```{r}
hchart(object = pp%>%filter(site == "Mafia"), "heatmap", hcaes(x = year, y = month, value = pp, group = site))
```

```{r ,eval=FALSE}
gb =ggplot(data = pp, aes(x = date, y = pp, col = site))+geom_line()
    plotly::ggplotly(gb)
```

```{r}
hchart(object = pp, "line", hcaes(x = date, y = pp, group = site))
```


```{r , fig.width=9}

pp.array = array(data = pp$pp, dim = c(length(month),length(year),length(sites)))

par(mfrow = c(2,2))
for (j in 1:length(sites)){
imagep(year, month, pp.array[,,j]%>%t(),filledContour = T, col = oceColors9A(120),  flipy = T, main = sites[j])
contour(year, month,pp.array[,,j]%>%t() , add = T)
}

```


### Temperature

```{r}
files = dir("./", pattern = "sst_")
sites = c("EEZ", "Mafia", "Pemba", "Zanzibar")
```


```{r}

sst = list()
for (i in 1:length(files)){

sst[[i]] = files[i] %>% readxl::read_excel()%>% 
  rename(date = 1, year = 2, sst = 3) %>% 
  mutate(month = month(date), 
         day = 15,
         site = sites[i], 
         date = make_date(year = year, month = month, day = day),
         variable = "sst") %>%
  arrange(date)
}

sst = sst %>% bind_rows()

```


```{r, fig.height=5, fig.width=10, eval=FALSE}
gg = ggplot()+
  geom_raster(data = sst, aes(x = year, y = month, fill =  sst), interpolate = T, na.rm = TRUE)+
  geom_contour(data = sst, aes(x = year, y = month, z =  sst), col = 1)+
  scale_y_reverse(breaks = 1:12)+
  scale_fill_gradientn(colours = oceColors9A(120))+
  facet_wrap(~site, scales = "free_y")

plotly::ggplotly(gg)
```

```{r}
hchart(object = sst%>%filter(site == "Mafia"), "heatmap", hcaes(x = year, y = month, value = sst, group = site))
```

```{r, ,eval=FALSE}
gb =ggplot(data = sst, aes(x = date, y = sst, col = site))+geom_line()
    plotly::ggplotly(gb)
```

```{r}
hchart(object = sst, "line", hcaes(x = date, y = sst, group = site))
```


```{r, fig.width=9}

sst.array = array(data = sst$sst, dim = c(length(month),length(year),length(sites)))

par(mfrow = c(2,2))
for (j in 1:length(sites)){
imagep(year, month, sst.array[,,j]%>%t(),filledContour = T, col = oceColors9A(120),  flipy = T, main = sites[j])
contour(year, month,sst.array[,,j]%>%t() , add = T)
}

```

## stitching the files
The row binding requires variables from different data frame must be similar, therefore, we change the variable chl,pp and sst to values and then stitch them together
```{r}
## bind them all. 
data = chl %>% 
  rename(value = chl)%>% 
    bind_rows(pp %>% rename(value = pp), 
              sst %>% rename(value = sst)) 

data = data %>% 
  mutate(month = month(date, label = TRUE, abbr = TRUE)) %>% 
  select(date, year, month, value, variable, site)
```

## Monthly variation

```{r}
hchart(object = data %>% filter(variable == "chl"),
       type = "spline",
       hcaes(x = date, y = value, group = site)) %>%
  hc_title(text = "Monthly Variation of Chlorophyll") %>%
  hc_subtitle(text = "Source of Data: MODIS")%>%
  hc_xAxis(title = list(text =NULL)) %>%
  hc_yAxis(title = list(text = "Concentration (mg/L)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```


```{r}
hchart(object = data %>% filter(variable == "pp"),
       type = "spline",
       hcaes(x = date, y = value, group = site))%>%
  hc_title(text = "Monthly Variation of Primary Productivity") %>%
  hc_subtitle(text = "Source of Data: MODIS")%>%
  hc_xAxis(title = list(text =NULL)) %>%
  hc_yAxis(title = list(text = "Primary productivity"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```



```{r}
hchart(object = data %>% filter(variable == "sst"),
       type = "spline",
       hcaes(x = date, y = value, group = site)) %>%
  hc_title(text = "Monthly Variation of Temperature") %>%
  hc_subtitle(text = "Source of Data: MODIS")%>%
  hc_xAxis(title = list(text = NULL)) %>%
  hc_yAxis(title = list(text = "Celcius (C)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```


```{r}
monthly.average = data %>% 
  group_by(site, variable, month) %>% 
  summarise(xbar = mean(value, na.rm = T) %>% round(digits = 2)) 
```

```{r}
hchart(object = monthly.average %>% filter(variable == "chl"), 
       type = "spline", 
       hcaes(x = month, y = xbar, group = site)) %>%
  hc_plotOptions(spline = list(
    dataLabels = list(enabled = FALSE),
    enableMouseTracking = TRUE))%>%
  hc_title(text = "Monthly Average Chlorophyll") %>%
  hc_subtitle(text = "Source of Data: Satellite Aqua MODIS") %>%
  hc_xAxis(title = NULL) %>% 
  hc_yAxis(title = list(text = "Concentration (mg/L)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```



```{r}
hchart(object = monthly.average %>% filter(variable == "pp"), 
       type = "spline", 
       hcaes(x = month, y = xbar, group = site)) %>%
  hc_plotOptions(spline = list(
    dataLabels = list(enabled = FALSE),
    enableMouseTracking = TRUE)) %>%
  hc_title(text = "Monthly Averge Primary Productivity") %>%
  hc_subtitle(text = "Source of Data: Satellite Aqua MODIS") %>%
hc_xAxis(title = NULL) %>% 
  hc_yAxis(title = list(text = "Primary Productivity"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```



```{r}
hchart(object = monthly.average %>% filter(variable == "sst"), 
       type = "spline", 
       hcaes(x = month, y = xbar, group = site)) %>%
  hc_plotOptions(spline = list(
    dataLabels = list(enabled = FALSE),
    enableMouseTracking = TRUE)) %>%
  hc_title(text = "Monthly Average Temperature") %>%
  hc_subtitle(text = "Source of Data: Satellite Aqua MODIS")%>%
  hc_xAxis(title = NULL) %>% 
  hc_yAxis(title = list(text = "Degree Celcisu (C)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = TRUE)
```

## bar plot
```{r}
hchart(object = data %>% filter(variable == "chl"), type = "bar", 
       hcaes(x = month, y = value, group = site)) %>%
  hc_title(text = "Monthly value of Chlorophyll") %>%
  hc_subtitle(text = "Source of Data: Satellite Aqua MODIS")%>%
  hc_xAxis(title = NULL) %>% 
  hc_yAxis(title = list(text = "COncentration (mg/L)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = FALSE)
  
```

```{r}

hchart(object = data %>% filter(variable == "sst"), type = "point", 
       hcaes(x = month, y = value, group = site)) %>%
  hc_title(text = "Monthly value of Sea Surface Temperature") %>%
  hc_subtitle(text = "Source of Data: Satellite Aqua MODIS")%>%
  hc_xAxis(title = NULL) %>% 
  hc_yAxis(title = list(text = "Celcius (C)"),
           opposite = FALSE,
           # minorTickInterval = "auto",
           minorGridLineDashStyle = "LongDashDotDot",
           showFirstLabel = FALSE,
           showLastLabel = FALSE)
  
```
